### ISSUE TITLE
Request: american english to British english plug-in

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/plugins#115]
it possible add a funtion to "does not allow add duplicate words to the list"?

**Comment by xylographe** [comment]
The branch from PR #117 includes a commit (7c413c62fbb26302144226e3426ab42b6459ad70) that prevents adding duplicates. Instead, the existing entry is selected. So you can choose if you want to keep the original or replace it (remove+add).

To add the `xab` branch to your local repo (assuming you have no local `xg-beta` branch),
```
git fetch -np "https://github.com/xylographe/plugins" "xab:xg-beta"
```
A DLL built from that branch is available in the `test version` folder in `AmericanToBritish.7z` from [this dropbox folder.](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0)

**Comment by xylographe** [comment]
@marb99 
Pushed into master branch (commit 92996f3eb51783f3f4f0facf95226faf9a570dc2).
Does this resolve the issue, or were you thinking of something else?

**Comment by marb99** [comment]
@xylographe 
works thank you
