### ISSUE TITLE
AmericanToBritish wait cursor

### ISSUE THREAD

**Issue by xylographe** [SubtitleEdit/plugins#121]
Apparently, `Cursor = Cursors.WaitCursor` in the [**`PluginForm_Shown`**](https://github.com/SubtitleEdit/plugins/blob/master/AmericanToBritish/DLL/PluginForm.cs#L136) event handler has no effect.
I tried recipes from CP and SO (ctor, Load, Application.DoEvents, etc.) but nothing seems to work.
Is there an alternative?

**Comment by ivandrofly** [comment]
Have you trying `Cursor.Current = Cursors.WaitCursor`?

**Comment by xylographe** [comment]
`Cursor.Current = Cursors.WaitCursor` does the trick! Thank you, @ivandrofly 

Resolved in commit a8a2154c1a47ec214c972a4a54bae21bfc8e78a8

BTW perhaps (unless there is some other issue that I haven't noticed) it is time for a new release of AmericanToBritish with the local word list feature?
