### ISSUE TITLE
AmericanToBritish edit

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/plugins#122]
Hi...

it is possible to allow edit lines in column "After"??

It would be very useful.

thanks

**Comment by xylographe** [comment]
Hello @marb99 

I've added 'Edit' (Ctrl-E or Return) and 'Reset' (Ctrl-R) menu items to the context menu of the before-after list. Left/Right arrows move focus to the next/previous edited paragraph.

Once you have edited an "After" text, it will not change (not even if you add/remove word pairs to/from the word list) until you use 'Reset'.

Commit in [branch am2br-edit-after](https://github.com/xylographe/plugins/tree/am2br-edit-after).
DLL in 'beta' folder of [AmericanToBritish.7z](https://www.dropbox.com/sh/thgk5507tteg6ze/AABgb8jgWBnz9LLgDHsECfika?dl=0) archive.

**Comment by marb99** [comment]
Hi. @xylographe

until now, work like a charm :+1: :100: :+1: 

I was waiting of this addition to dll

thank you very much

**Comment by xylographe** [comment]
Added in commit f27a3a67ca466cc0d4f61c556bc2806b472e9866
