### ISSUE TITLE
Netflix rules - wrong word and minimum

### ISSUE THREAD

**Issue by Yamato-ua** [SubtitleEdit/plugins#129]
"Minimum duration: 5/6 sec (833.3. ms)"
I think it's better to set it to 833, because now it flags 20-frame subtitles which is official minimum in frames according to Netflix site. https://backlothelp.netflix.com/hc/en-us/articles/215758617-Timed-Text-Style-Guide-General-Requirements

And there's also this small oversight:
"Minimum 17 characters per second" should be ""Maximum 17 characters per second" in results list.

**Comment by niksedk** [comment]
thx for the info :)

Should be fixed in commit 90d8046a4cf0858e721ba64e1bc1b1fbc2025e5e
