### ISSUE TITLE
Plugin interface

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/plugins#133]
I think we should change the "Form" type passed in DoAction to "type", the reason is that will allow us to  access the member of invoker (Main.cs) via reflection...

I want to write a plugin that will allow modifying the UI content of main-form.
Since "Form' is a superclass of Main we can't access Main.cs member directly.

Also introduce a new method in IPlugin.cs that will execute as soon as the plugin is loaded by SubtitleEdit.exe without needing to be invoked by user action... 

 /cc @niksedk

**Comment by diomed** [comment]
so this ain't gonna happen at all, huh?

**Comment by ivandrofly** [comment]
Please check you email :) @diomed
