### ISSUE TITLE
Lines Unbreaker

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/plugins#134]
Could you let it save my choice?
like keep "Skip Dialog" not selected and save the number of letters?
Maybe it can take the number from the selected Man Char per line from settings?
And if i want it to be 42 after Unbreaking what is the number i should choose?
@ivandrofly

**Comment by OmrSi** [comment]
Yeah, I seem to have to use 43, does it consider the line break as a letter?

**Comment by ivandrofly** [comment]
> Yeah, I seem to have to use 43, does it consider the line break as a letter?

yeah, but that can be handled too :)

**Comment by OmrSi** [comment]
Great. :)

**Comment by OmrSi** [comment]
it's a really great tool.
Thanks a lot.
it saved a lot of work. :D

**Comment by ivandrofly** [comment]
New version is available :) @OmrSi

**Comment by OmrSi** [comment]
Thanks a lot. :D
Sorry about this. :'D

just one thing left, can you let it save the number of letters you use?
or get it from your settings?
cause now you have to put it every time

**Comment by OmrSi** [comment]
Thanks a lot. :D
It works perfectly.

Sorry about this. :'D
just one thing left, can you let it save the number of letters you use?
or get it from your settings?
cause now you have to put it every time

**Comment by ivandrofly** [comment]
@OmrSi #140

**Comment by OmrSi** [comment]
Yep. it saves the number now.
One thing, when you open the plugin, it doesn't show you the line immediately, you have to check\uncheck one of the options or click on the number then press enter...
can't you make it show them once opened or add a button to apply to show them then press OK?
and it's working on "Smaller than" basis, isn't it better to use "Equal to or smaller than..."?
Thanks for the great Work!

**Comment by ivandrofly** [comment]
Done :) /cc @OmrSi

**Comment by OmrSi** [comment]
Mere awesomeness :)
I believe it is now at its best :D
Thank You so much!
