### ISSUE TITLE
Binary image compare Error

### ISSUE THREAD

**Issue by IsaacC21** [SubtitleEdit/plugins#142]
in the Binary image compare when working with Hebrew there seems to be an error since hebrew script doesn't show up

![1-8-2018 5-21-10 pm](https://user-images.githubusercontent.com/35211548/34695336-73179334-f498-11e7-966a-9675549278ae.png)

**Comment by IsaacC21** [comment]
Also is there any way to just export the image? I'd like to try and use Abby OCR on the image that the program created in the picture above I think it would be helpful

**Comment by niksedk** [comment]
SE is only made for clean subtitles - not hard-coded subs, sorry.

You can right click in the list view in the OCR window and export to multiple different formats.
