### ISSUE TITLE
Deepl always starts anew after "Too many requests"

### ISSUE THREAD

**Issue by mkver** [SubtitleEdit/plugins#143]
Hello,

the last release of Deepl brought two advances (a more useful error message and somehow the translation now handles " " in the input better (before it it would often neither translate it nor put the original text in the output, but rather something like `\"`)), but it also has a disadvantage: If one encounters the "Too many requests" error, waits for some time and attempts to resume the translation, the plugin actually restarts the process: It ignores the translations already made and starts again from the first subtitle on. The result is that I often run into the same error again and the only way to translate the subs is by splitting the file into smaller parts and process them individually.

Greetings
mkver

**Comment by niksedk** [comment]
@mkver: How does version 0.9 of th deepL plugin work for you?

**Comment by mkver** [comment]
After restarting there are usually two lines that stay completely untranslated (probably because SE sends multiple requests for translations in parallel). Apart from that it works well. I can live with this restriction -- translating a few lines manually is no big deal. If you feel that this is good enough, you can close this issue.

**Comment by diese31diese** [comment]
Hi,
would it indeed be possible to improve the DeepL plugin: I had also found the same solution as mkver to know how to split into 2, 3 or 4 parts my subtitles (in particular those of film which make several thousand lines of subtitles ; for an episode of a series of 30 minutes that went, that was translated in only one time). However even when cutting out the DeepL subtitles returns the error "too many query" and there patience is required in addition to actually having some lines untranslated.

**Comment by diese31diese** [comment]
Perhaps it would be possible to implement a subtitle line selection function to launch subtitles only as you go along, and also have a function to return and restart a translation without having to start all over again ?!
Or maybe make the plugin have some configurable delay before asking DeepL to translate the following lines so as not to send too much text at once and get the "too many request" error

**Comment by 1024mb** [comment]
Now it's not working. It doesn't translate anything.

**Comment by niksedk** [comment]
It's possible to start from any line, so if you got the first 800 lines first time, then start in line 801 next time (but you must merge manually).

@1024mb: thx, should be fixed.
