### ISSUE TITLE
Lines Unbreaker char count

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/plugins#160]
@ivandrofly It seems to add 1 to length after:
![screenshot 125](https://user-images.githubusercontent.com/20923700/51625271-650bfe00-1f45-11e9-9595-5241ccd2ec5e.png)

Or did I get something wrong?

**Comment by ivandrofly** [comment]
> @ivandrofly It seems to add 1 to length after:

I think your problem is fixed in latest release. Can you please test?

**Comment by OmrSi** [comment]
@ivandrofly It is. Thanks a lot. :D
