### ISSUE TITLE
CopyPaste plug-in fail matching italic and bold tags from original subtitle

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/plugins#163]
CopyPaste plug-in fail matching italic and bold tags from original subtitle

sometimes places the tags in others lines in sub translared, others times simple remove the tags after translation

**Comment by niksedk** [comment]
Could you provide an text that displays this behavior?

**Comment by marb99** [comment]
@niksedk 

here ist it used DeepL

[The.Dictators.Playbook.zip](https://github.com/SubtitleEdit/plugins/files/2902902/The.Dictators.Playbook.zip)

![capturar](https://user-images.githubusercontent.com/7856897/53373462-6a49d780-394d-11e9-8d9c-cf8354f01cfa.PNG)

**Comment by niksedk** [comment]
thx for the info - fixed an issue regarding italics...
How is Copy-Paste translate 0.5 ?

**Comment by marb99** [comment]
for now it's ok, but I need to test more if I find any errors, I'll let you know ;)

**Comment by niksedk** [comment]
Translate plugins updated to fix issue with blank line.
