### ISSUE TITLE
[Bug] Lines Unbreaker crash

### ISSUE THREAD

**Issue by marb99** [SubtitleEdit/plugins#165]
Lines Unbreaker crash

![3](https://user-images.githubusercontent.com/7856897/54482911-923ca480-4842-11e9-94c0-252529d595f6.gif)

**Comment by ivandrofly** [comment]
Please can you try the latest version?

**Comment by marb99** [comment]
@ivandrofly  sorry for answering only now

but version 2 still crash and the error is the same above

**Comment by ivandrofly** [comment]
> @ivandrofly sorry for answering only now
> 
> but version 2 still crash and the error is the same above

Can you please go to plugin folder and delete any configuration file related to "lines unbreak" .xml

**Comment by marb99** [comment]
@ivandrofly 

I don't have any config file in plugin folder, and still crash

**Comment by ivandrofly** [comment]
> I don't have any config file in plugin folder, and still crash

Updated, try the latest version.

**Comment by OmrSi** [comment]
@ivandrofly Any chance you could add checkboxes like the ones in FCE?
It would help to choose what to unbreak rather than having to close it and unbreak the line then get back to see the others...

**Comment by ivandrofly** [comment]
> having to close it

What do you mean?

**Comment by OmrSi** [comment]
I mean when you have a bunch of lines and you can't use skip moods or narrator cause you might miss something, as in Arabic some lines could be mistaken for that, and you just want to break, for example, 4 out of 10 lines, you'd have to memorize the numbers and unbreak manually, So a checkboxes would make it easier.

**Comment by marb99** [comment]
@ivandrofly 

work now, thanks :)

**Comment by ivandrofly** [comment]
> I mean when you have a bunch of lines and you can't use skip moods or narrator cause you might miss something, as in Arabic some lines could be mistaken for that, and you just want to break, for example, 4 out of 10 lines, you'd have to memorize the numbers and unbreak manually, So checkboxes would make it easier.

Check latest version

**Comment by OmrSi** [comment]
Wow, this is exactly what I had in mind. :D
Thank you very much. <3
