### ISSUE TITLE
Dropbox plugins no longer working

### ISSUE THREAD

**Issue by OmrSi** [SubtitleEdit/plugins#181]
Well, after updating the Dropbox plugins, they stopped working. :)
When trying to save or load a subtitle for the first time, this shows up:

![image](https://user-images.githubusercontent.com/20923700/96366977-b580b180-1153-11eb-8d2f-fed9605d1470.png)

@ivandrofly I think it has something to do with the changes you made.
Is there something I have to do first?

**Comment by ivandrofly** [comment]
I think the dropbox api has changed, 'cause I revert the commit and it still gives the same error!!!

**Comment by OmrSi** [comment]
Hmm. Well, if you go back to the old version, it works fine.
Also, if you go back to the old version and just generate the token file, the file works fine with the new version.

**Comment by ivandrofly** [comment]
@OmrSi  https://github.com/SubtitleEdit/plugins/commit/1d84aab39ff4fa744cf0a4e28cc085e3653d9b74#commitcomment-38737213 😄

**Comment by OmrSi** [comment]
You need to create an app and add this?
