### ISSUE TITLE
Google screen-scraping is not working (no updated plugin)

### ISSUE THREAD

**Issue by Sopor** [SubtitleEdit/plugins#186]
It seems that Google screen-scraping is not working.

This time i did check the plugins and i'm at version 1.03 and Subtitle Edit is version 3.6.0.

It will only give me back empty lines :(

**Comment by niksedk** [comment]
Could you try the GT screen-scraper 1.04 ? 
If it's not working, then press F2 until the browser windows shows, and accept cookies...

Let me know if/how it works :)

**Comment by Sopor** [comment]
I got stuck at this screen and even if i pressed the X the window doesn't close. I was forced to kill the task.

![image](https://user-images.githubusercontent.com/5789283/116005918-60918c80-a609-11eb-8e86-b763921638aa.png)

After restarting Subtitle Edit it now seems to work :)

**Comment by niksedk** [comment]
Google Translate screen-scraper updated to 1.05... will now auto detect "accept cookies page" and auto switch to the browser, and switch back to list view again when pressing "Translate".

I've tested a few subtitles... no subtitle row losses. You can try to lower the bulk max byte size to e.g. 50.

**Comment by Sopor** [comment]
I think you will find it here:
c:\Users\<user>\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy

I have it set to 500now, but i will try 50.

**Comment by Sopor** [comment]
Now i get those missing lines again even at 50 bytes. It is more spread out comparing to using 500.

500:
![image](https://user-images.githubusercontent.com/5789283/118186180-b6ee3000-b43d-11eb-8968-3a8b24d01620.png)

50:
![image](https://user-images.githubusercontent.com/5789283/118186315-e309b100-b43d-11eb-8a9f-3353d60ba5a5.png)

**Comment by niksedk** [comment]
Still don't get blank lines... is it a specific subtitle or how can I re-create it?

**Comment by Sopor** [comment]
@niksedk Check your inbox!

**Comment by niksedk** [comment]
thx for the file :)
OK, was a problem with "&" and a redirect... plugin updated, should work better now.

**Comment by Sopor** [comment]
It is working again, thanks!
