### ISSUE TITLE
ASSA Draw: Support Rectangle / Square

### ISSUE THREAD

**Issue by LeonCheung** [SubtitleEdit/plugins#195]
Very nice to make things like clips and background boxes. It would be even better to support rounded corners! :D

**Comment by niksedk** [comment]
Rectangle support is included in v0.20 :)

**Comment by LeonCheung** [comment]
Cool! It's really handy. Thanks a lot for that!!!

**Comment by LeonCheung** [comment]
One more thing: 
![image](https://user-images.githubusercontent.com/494788/148650850-ff36d92e-4394-43d2-925c-c5caff389b39.png)

How to reproduce: Draw some shape then hit Enter twice.

**Comment by LeonCheung** [comment]
Another thing is (I think it's an existing issue), when drawing the primary shapes, for example, the rectangle, normally we can just click LMB one more time to confirm the drawing, without hitting Enter, right? But when the gap between the two LMB clicks is less than 1 sec or shorter, it doesn't work.
