### ISSUE TITLE
[URGENT] HELP

### ISSUE THREAD

**Issue by ivandrofly** [SubtitleEdit/plugins#22]
@niksedk would you please force push your `local master branch`, something bad happen while I was pushing.

Run following command to restore `master`:
`git push --force origin master:master` /cc @niksedk 

**Note: Do not update your `local master` branch with origin's `master branch` otherwise all the commit will be lost**

**Comment by niksedk** [comment]
Wow, yes something bad happened... I'll hopefully have time to look at it tonight

**Comment by ivandrofly** [comment]
If you still have you local master branch can be easy to fix by following the instruction above

**Comment by niksedk** [comment]
Don't have it on this computer... and I will take backup + read up on the git first...

**Comment by ivandrofly** [comment]
:+1:

**Comment by ivandrofly** [comment]
I've also try to check user which has forked this repository none of them seems to have last updates

**Comment by ivandrofly** [comment]
:smile: I have file history running it should be there

**Comment by ivandrofly** [comment]
@niksedk was this your last push? https://github.com/SubtitleEdit/plugins/commit/14dab576cbac22b1740c54be5fd7cf5bc07e181e

**Comment by niksedk** [comment]
I'm glad ´git push --force origin master:master´ worked fine :)
git should have some undo...

**Comment by ivandrofly** [comment]
:+1:
