### ISSUE TITLE
Any method to directly open Subtitle Edit in Tools-batchconvert window?

### ISSUE THREAD

**Issue by vsrawat** [SubtitleEdit/plugins#226]
I am using it mostly to extract subtitles from mpv files. I run it, main window opens, I click on Tools-batchconvert, then I do it.

It would reduce these steps if I could put some opening shortcut option to directly open it in batch convert window.

I don't want command line conversion, I find the UI window convenient.

Any method?

Thanks.

**Comment by niksedk** [comment]
You can start `Subtitle Edit` with the parameter `/batchconvertui`

**Comment by vsrawat** [comment]
Yes, I did that, and it worked. Thanks for the prompt and correct reply.

Now, it is always opening in /batchconvertui window. How do I go to main 
window if I ever wanted to use some other feature of the program?

Seems I will have to dig through c:\program files to click on the actual 
exe file instead of shortcut.

To make it convenient,olease consider adding some icon on the 
/batchconvertui window to open main window.

Please mark this issue as closed.

Thanks.

**Comment by niksedk** [comment]
>Now, it is always opening in /batchconvertui window. How do I go to main
>window if I ever wanted to use some other feature of the program?


You can make two shortcuts.
