### ISSUE TITLE
Inaccuracies Subtitle Edit

### ISSUE THREAD

**Issue by Wolf180990** [SubtitleEdit/plugins#227]
Hi, I am writing to ask you if you can improve the recognition of words, or unrecognized phrases, avoiding a mandatory correction by the user. 

for example, multiple words of a sentence are represented together and must be separated by the user, or one word is not recognized and is exchanged for another, or even, this symbol "|" is used as a substitute symbol for, I, i or !.

ps: I'm using version 3.6.13 with Tesseract 5.3.0

**Comment by niksedk** [comment]
Yes, you can add names, words and even phrases and regular expressions.

See Options - word lists (or directly in the OCR window)
![image](https://github.com/SubtitleEdit/plugins/assets/1261331/0d99b41c-80a9-4be9-9e0c-e0718247d024)

The advanced settings are only available in you edit the "ocr fix replace list" files directly - see `eng_OCRFixReplaceList.xml` for an example.
