### ISSUE TITLE
Google translation in batch

### ISSUE THREAD

**Issue by Nickyg001** [SubtitleEdit/plugins#229]
How is batch conversion of many files possible e.g. *.vtt to *.srt, would it also be possible to do Automatic Subtitle Translation in batch mode on a set of files, or entire folders??
It would be very useful.

**Comment by niksedk** [comment]
You can convert to specific format via Tools - Batch convert:

![image](https://github.com/SubtitleEdit/plugins/assets/1261331/e8ac1f48-4540-41b2-83d0-6ef4bc37df09)


"Batch translate"  does not make sense as it is limited :(

**Comment by Nickyg001** [comment]
"Batch translate" does not make sense as it is limited :(

explain this to me? do you mean the google limit of 5000 characters? But if the translation is done file by file, the 5000 characters should be reset to each new translation of the file or not?

**Comment by niksedk** [comment]
Google only allows a certain amount of characters from in IP per day... I would get *so* many people complaining about this!
