### ISSUE TITLE
English To Bahasa Indonesia Error

### ISSUE THREAD

**Issue by rikyuking** [SubtitleEdit/plugins#235]
https://i.postimg.cc/Hs6rJyHK/c-Uy-XO35yo-E.png

please fix DeepL translator....
English to Bahasa Indonesia

**Comment by niksedk** [comment]
Please just attach images directly:

![c-Uy-XO35yo-E](https://github.com/SubtitleEdit/plugins/assets/1261331/ad0e2543-4e62-42ae-a690-d263003a12c8)

Also, what is the problem?

**Comment by niksedk** [comment]
Ah, OK. Indonesian should no longer be Finnish.... update the plugin to 1.7

**Comment by rikyuking** [comment]
> Ah, OK. Indonesian should no longer be Finnish.... update the plugin to 1.7

thanks ... :)
