### ISSUE TITLE
DeepL ap translation Plugin ?

### ISSUE THREAD

**Issue by diomed** [SubtitleEdit/plugins#237]
could you maybe make addition or a plugin that would utilize DeepL api for translation?

https://www.deepl.com/pro-api?cta=header-pro-api

**Comment by niksedk** [comment]
This is fairly old:
![image](https://github.com/SubtitleEdit/plugins/assets/1261331/51b995c5-ceca-4cbe-85a6-70890d1159bf)


Latest beta has DeepL built directly in:
![image](https://github.com/SubtitleEdit/plugins/assets/1261331/dc81bdcb-cdb8-4140-8a9d-cd4fdf1d0f9e)
