### ISSUE TITLE
AmericanToBritish with local word list

### ISSUE THREAD

**Issue by xylographe** [SubtitleEdit/plugins#34]
[branch americanBritish]

Perhaps, there could be three radio buttons?
- Use built-in list
(Preselected if the local word list does not exist).
- Use local list
(Preselected if the local word list exists, and the `NoBuiltIn` attribute is set to `"true"`).
- Use both lists
(Preselected if the local word list exists, and the `NoBuiltIn` attribute is absent or set to `"false"`).

In the case of "Use both lists" the local word list would be applied first, followed by applying the built-in word list, which effectively allows users to overwrite single entries in the list, if desired.

The "Disable built-in" check box would become unnecessary.

**Comment by ivandrofly** [comment]
Done in https://github.com/SubtitleEdit/plugins/pull/36
